### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by rishabh7m** [dhis2/dhis2-android-dashboard#16]
While importing in android studio got the following error.
Error:Configuration with name 'default' not found.

Steps:-
1. Import project.
2. Selected dhis2-android-dashboard directory

**Comment by erlingfjelstad** [comment]
Hi,
Make sure that your SDK project is in 2.22-legacy branch and try building again. Let me know if it works.

**Comment by rishabh7m** [comment]
Hi @erlingfjelstad , can you please elaborate this? I was searching for the same and came to know that there is dhis2-android-sdk. So, should I use this sdk instead of android Sdk?

**Comment by erlingfjelstad** [comment]
Try to switch to legacy branch in dashboards project and check if it builds. Sorry, we're partially in a refactoring stage right now

**Comment by rishabh7m** [comment]
Still the same error.

**Comment by erlingfjelstad** [comment]
Did you sync gradle?

**Comment by arazabishov** [comment]
Hi rishabh7m, 

Here are several steps you should consider:
1) Make sure you are on legacy branch
2) If you first imported project from master branch and then switched to legacy, try to invalidate cache and restart android studio.

**Comment by rishabh7m** [comment]
Now I am getting different error: - gradle dsl method not found 'compile()'

**Comment by arazabishov** [comment]
While importing the project to android studio, did you select to use "gradle wrapper" or global gradle installation for builds?

**Comment by rishabh7m** [comment]
Global. Gradle wrapper was not showing any files while selecting gradle home

**Comment by arazabishov** [comment]
You should select gradle wrapper option and leave gradle home property blank. Also make sure that when you import project, android studio is pointed to app/build.gradle.

**Comment by rishabh7m** [comment]
Android studio is not allowing to keep gradle home path empty.

**Comment by Dvik** [comment]
i've pointed to app/build.gradle while importing the project and had selected the gradle wrapper option.
However, i get the error that sdk location is not defined but in local.properties i have this : sdk.dir=C:\Users\Divya\AppData\Local\Android\sdk.

**Comment by Dvik** [comment]
Built successfully. Had just pointed to the wrong build.gradle earlier.

**Comment by mayank-kgp** [comment]
@ArazAbishov 
Hi...
    Which server url,username and password to use for entering in the app?

**Comment by Dvik** [comment]
You can try to use it with demo server:
https://play.dhis2.org/demo
Username: admin
Password: district

**Comment by mayank-kgp** [comment]
@Dvik  Thanks
