### ISSUE TITLE
A bug in activity Interpretations

### ISSUE THREAD

**Issue by yiyuanliu** [dhis2/dhis2-android-dashboard#18]
When I try to refresh or edit the content in activity Interpretations(Edit the content also cause refresh).The app stoped because of a NullPointerException. 
<img width="854" alt="nullpointerexception" src="https://cloud.githubusercontent.com/assets/13906397/13518768/57a797ca-e20c-11e5-8fe3-5000bacb40b8.PNG">

**Comment by yiyuanliu** [comment]
![screenshot-min](https://cloud.githubusercontent.com/assets/13906397/13519135/a2a7d570-e20f-11e5-84b9-b9efcc8a059a.png)

My phone is Nexus5 with android 6.0.The server is https://play.dhis.org/demo.

**Comment by Dvik** [comment]
Looks like the api is returning null for lastUpdated.

**Comment by arazabishov** [comment]
@Dvik That's right. This issue is fixed now in legacy branch: d28d06c540dcf87b66c259cf2a13528a1b629f5b
